---
- name: restart minecraft
  community.docker.docker_compose_v2:
    project_src: "{{ minecraft_data_dir }}"
    state: restarted
  become: true
  become_user: "{{ minecraft_user }}"

- name: recreate minecraft
  community.docker.docker_compose_v2:
    project_src: "{{ minecraft_data_dir }}"
    state: present
    pull: always
    recreate: always
  become: true
  become_user: "{{ minecraft_user }}"